Train:
  batch_size: 32
  learning_rate: 0.01
  reg: 0.0005
  epochs: 1
  steps: [40, 60, 80]
  warmup: 2
  momentum: 0.9
  weights_path: na

network:
  model: AlexNet-upprojection

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.999
  save_best: True

loss:
  loss_type: Focal # CE or Focal or other loss functions