Train:
  batch_size: 32
  learning_rate: 0.001
  stepdown_factor: 0.1
  reg: 0.0005
  epochs: 50
  steps: [20, 30, 40]
  warmup: 5
  momentum: 0.9
  weights_path: na
  model_class: VGG-16Based-UpConvolution # other possible values Resnet50BasedModel, Resnet50BasedUpProjModel

network:
  model: vgg-16-upconv

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.999
  save_best: True

loss:
  loss_type: Focal # CE or Focal or other loss functions