Train:
  batch_size: 32
  learning_rate: 0.01
  stepdown_factor: 0.1
  reg: 0.0005
  epochs: 10
  steps: [40, 60, 80]
  warmup: 2
  momentum: 0.9
  weights_path: na
  model_class: Resnet50BasedUpProjModel # other possible values Resnet50BasedModel, Resnet50BasedUpProjModel

network:
  model: resnetv2

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.999
  save_best: True

loss:
  loss_type: Focal # CE or Focal or other loss functions