Train:
  batch_size: 32
  learning_rate: 0.0001
  stepdown_factor: 0.5
  reg: 0.005
  epochs: 50
  steps: [10, 20, 35]
  warmup: 5
  momentum: 0.9
  weights_path: na
  model_class: VGG-19Based-UpConvolution # other possible values Resnet50BasedModel, Resnet50BasedUpProjModel

network:
  model: vgg-19-upProjection

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.999
  save_best: True

loss:
  loss_type: Focal # CE or Focal or other loss functions