Train:
  batch_size: 2
  learning_rate: 0.00001
  stepdown_factor: 0.1
  reg: 0.0005
  epochs: 10
  steps: [ 10, 20, 30 ]
  warmup: 2
  momentum: 0.9
  weights_path: na
  model_class: Resnet50BasedUpProjModel # other possible values Resnet50BasedModel, Resnet50BasedUpProjModel
  start_epoch: 0
  optimizer: Adam # or SGD Default is Adam

network:
  model: resnetv2

data:
  dataset: nyu # cityscape or nyu
  apply_augmentations: True
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.999
  save_best: True

loss:
  loss_type: Focal # CE or Focal or other loss functions