Train:
  batch_size: 32
  learning_rate: 0.01
  reg: 0.0005
  epochs: 1
  steps: [20, 30, 40]
  warmup: 5
  momentum: 0.9
  weights_path: na

network:
  model: AlexNet-upprojection

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.999
  save_best: True

loss:
  loss_type: inverseHuber # CE or Focal or other loss functions