Train:
  batch_size: 32
  learning_rate: 0.01
  reg: 0.0005
  epochs: 10
  steps: [20, 50]
  warmup: 4
  momentum: 0.9

network:
  model: ResNet-32

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.999
  save_best: True

loss:
  loss_type: Focal # CE or Focal or other loss functions